In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
names = pd.read_table('mimic_synthetic_feat.name',sep='\n',header=None)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [4]:
name_col = names[0].tolist()

In [5]:
name_col

['SUBJECT_ID',
 'HADM_ID',
 'ADMITTIME',
 'DISCHTIME',
 'INSURANCE',
 'LANGUAGE',
 'RELIGION',
 'MARITAL_STATUS',
 'ETHNICITY',
 'GENDER',
 'AGE',
 'HR_MIN_DAY1',
 'HR_MAX_DAY1',
 'HR_MEAN_DAY1',
 'SYS_BP_MIN_DAY1',
 'SYS_BP_MAX_DAY1',
 'SYS_BP_MEAN_DAY1',
 'DIAS_BP_MIN_DAY1',
 'DIAS_BP_MAX_DAY1',
 'DIAS_BP_MEAN_DAY1',
 'MEAN_BP_MIN_DAY1',
 'MEAN_BP_MAX_DAY1',
 'MEAN_BP_MEAN_DAY1',
 'RESP_RATE_MIN_DAY1',
 'RESP_RATE_MAX_DAY1',
 'RESP_RATE_MEAN_DAY1',
 'TEMP_MIN_DAY1',
 'TEMP_MAX_DAY1',
 'TEMP_MEAN_DAY1',
 'SPO2_MIN_DAY1',
 'SPO2_MAX_DAY1',
 'SPO2_MEAN_DAY1',
 'GLUCOSE_MIN_DAY1',
 'GLUCOSE_MAX_DAY1',
 'GLUCOSE_MEAN_DAY1',
 'HR_MIN_DAY2',
 'HR_MAX_DAY2',
 'HR_MEAN_DAY2',
 'SYS_BP_MIN_DAY2',
 'SYS_BP_MAX_DAY2',
 'SYS_BP_MEAN_DAY2',
 'DIAS_BP_MIN_DAY2',
 'DIAS_BP_MAX_DAY2',
 'DIAS_BP_MEAN_DAY2',
 'MEAN_BP_MIN_DAY2',
 'MEAN_BP_MAX_DAY2',
 'MEAN_BP_MEAN_DAY2',
 'RESP_RATE_MIN_DAY2',
 'RESP_RATE_MAX_DAY2',
 'RESP_RATE_MEAN_DAY2',
 'TEMP_MIN_DAY2',
 'TEMP_MAX_DAY2',
 'TEMP_MEAN_DAY2',
 'SPO2_MIN_DAY2',
 'SPO2_MAX_DAY2',
 'SPO2_MEAN_DAY2',
 'GLUCOSE_MIN_DAY2',
 'GLUCOSE_MAX_DAY2',
 'GLUCOSE_MEAN_DAY2',
 'ICU',
 'Tuberculosis',
 'Immuniz/scrn',
 'AcuteMI',
 'Coronathero',
 'Chestpain',
 'Pulmhartdx',
 'Othheartdx',
 'Conduction',
 'Dysrhythmia',
 'Cardiaarrst',
 'chf;nonhp',
 'AcuteCVD',
 'Hd/nckcancr',
 'Precereoccl',
 'OtherCVD',
 'TIA',
 'LateeffCVD',
 'Peripathero',
 'Aneurysm',
 'Artembolism',
 'Otcirculdx',
 'Phlebitis',
 'Varicosevn',
 'Esophcancer',
 'Hemmorhoids',
 'Othveindx',
 'Pneumonia',
 'Influenza',
 'Tonsillitis',
 'Bronchitis',
 'Otuprspin',
 'COPD',
 'Asthma',
 'Asppneumon',
 'Stomchcancr',
 'Pleurisy',
 'Adltrespfl',
 'Lungexternl',
 'Othlowresp',
 'Otupprresp',
 'Intestinfct',
 'Teethdx',
 'Mouthdx',
 'Esophgealdx',
 'Gasduoulcer',
 'Coloncancer',
 'Gastritis',
 'Otdxstomch',
 'Appendicitis',
 'Abdomhernia',
 'Ulceratcol',
 'Intobstruct',
 'Diverticulos',
 'Anal/rectal',
 'Peritonitis',
 'Biliarydx',
 'Rctm/anusca',
 'Othliverdx',
 'Pancreasdx',
 'GIhemorrhag',
 'Gastroent',
 'OtherGIdx',
 'Nephritis',
 'Acrenlfail',
 'Chrrenfail',
 'UTI',
 'Liver/ibdca',
 'Urinstone',
 'Otdxkidney',
 'Otdxbladdr',
 'OtherGUdx',
 'BPH',
 'Infmalegen',
 'Othmalegen',
 'Breastdx',
 'PID',
 'Endometrios',
 'Pancreascan',
 'Prolapse',
 'Menstrualdx',
 'Ovariancyst',
 'Menopausldx',
 'Feminfertil',
 'Otfemalgen',
 'Contraceptiv',
 'Spontabortn',
 'Inducabortn',
 'Abortcompl',
 'GI/peritcan',
 'Ectopicpreg',
 'Otpregcomp',
 'Hemorrpreg',
 'HTNinpreg',
 'Earlylabor',
 'Longpregncy',
 'DMinpreg',
 'Malposition',
 'Pelvicobstr',
 'Prevc-sectn',
 'Brnch/lngca',
 'Fetaldistrs',
 'Amniosdx',
 'Umbilcord',
 'OB-relatedperintrauma',
 'Otcomplbir',
 'Nmlpreg/del',
 'Skininfectn',
 'Otinflskin',
 'Ulcerskin',
 'Septicemia',
 'Otrespirca',
 'Othskindx',
 'Infectarth',
 'Rheumarth',
 'Osteoarthros',
 'Otjointdx',
 'Backproblem',
 'Osteoporosis',
 'Pathologfx',
 'Acqfootdef',
 'Otacqdefor',
 'Bone/ctcncr',
 'SLE',
 'Otconntiss',
 'Otbonedx',
 'Cardiacanom',
 'GIconganom',
 'guconganom',
 'Nervcongan',
 'Otconganom',
 'Liveborn',
 'Lowbirthwt',
 'Skinmelanom',
 'Birthasphyx',
 'Respdistres',
 'Perintjaund',
 'Birthtrauma',
 'Otperintdx',
 'Jointinjury',
 'Fxhip',
 'Spincorinj',
 'Fxskullfac',
 'Fxarm',
 'Non-epithca',
 'Fxleg',
 'Othfracture',
 'Sprain',
 'Intracrninj',
 'Crushinjury',
 'Opnwndhead',
 'Opnwndextr',
 'Complicdevi',
 'Complicproc',
 'Superficinj',
 'Breastcancr',
 'Burns',
 'Poisonpsych',
 'Poisnotmed',
 'Poisnnonmed',
 'Otherinjury',
 'Syncope',
 'FUO',
 'Lymphenlarg',
 'Gangrene',
 'Shock',
 'Uteruscancr',
 'Nausea/vomit',
 'Abdomnlpain',
 'Fatigue',
 'Allergy',
 'Socialadmin',
 'Exam/eval',
 'Otaftercare',
 'Otherscreen',
 'Unclassified',
 'Cervixcancr',
 'ECodes:Cut/pierce',
 'ECodes:Drowning/submersion',
 'ECodes:Fall',
 'ECodes:Fire/burn',
 'ECodes:Firearm',
 'ECodes:Machinery',
 'ecodes:motorvehicletraffic(mvt)',
 'ECodes:Pedalcyclist-notMVT',
 'ECodes:Pedestrian-notMVT',
 'ecodes:transport-notmvt',
 'ECodes:Natural/environment',
 'ECodes:Overexertion',
 'ECodes:Poisoning',
 'ECodes:Struckby-against',
 'ECodes:Suffocation',
 'ECodes:Adverseeffectsofmedicalcare',
 'ECodes:Adverseeffectsofmedicaldrugs',
 'ECodes:Otherspecifiedandclassifiable',
 'ecodes:otherspecified-nec',
 'ECodes:Unspecified',
 'ECodes:Placeofoccurrence',
 'Ovarycancer',
 'Femgenitca',
 'Prostatecan',
 'Othbactinf',
 'Testiscancr',
 'Malgenitca',
 'Bladdercncr',
 'Kidny/rnlca',
 'Urinyorgca',
 'Brain/nscan',
 'Thyroidcncr',
 'Hodgkin-sds',
 'Non-Hodglym',
 'Leukemias',
 'Mycoses',
 'Multmyeloma',
 'Otprimryca',
 '2ndarymalig',
 'Maligneopls',
 'Neoplsmunsp',
 'Maintchem/r',
 'Bnignutneo',
 'Otbnignneo',
 'Thyroiddsor',
 'DiabMelnoc',
 'HIVinfectn',
 'DiabMelw/cm',
 'Otendodsor',
 'Nutritdefic',
 'Hyperlipidem',
 'Gout/otcrys',
 'Fluid/elcdx',
 'Cysticfibro',
 'Immunitydx',
 'Otnutritdx',
 'Anemia',
 'Hepatitis',
 'Acutp-hanm',
 'Sicklecell',
 'Coag/hemrdx',
 'Whtblooddx',
 'Othematldx',
 'Adjustmentdisorders',
 'Anxietydisorders',
 'Attention-deficit/conduct/disruptivebeha',
 'Delirium/dementia/amnestic/othercognitiv',
 'Developmentaldisorders',
 'Disordersusuallydiagnosedininfancy/ch',
 'ImpulsecontroldisordersNEC',
 'Mooddisorders',
 'Personalitydisorders',
 'Schizophreniaandotherpsychoticdisorde',
 'Alcohol-relateddisorders',
 'Substance-relateddisorders',
 'Suicideandintentionalself-inflictedin',
 'Screeningandhistoryofmentalhealthan',
 'Miscellaneousmentaldisorders',
 'Viralinfect',
 'Meningitis',
 'Encephalitis',
 'OthCNSinfx',
 'Parkinson-s',
 'Othinfectns',
 'MS',
 'OtheredCNS',
 'Paralysis',
 'Epilepsy/cnv',
 'Headache/mig',
 'Coma/brndmg',
 'Cataract',
 'Retinaldx',
 'Glaucoma',
 'Blindness',
 'SexualInfxs',
 'Eyeinfectn',
 'Othereyedx',
 'Otitismedia',
 'Dizziness',
 'Othereardx',
 'Othnervdx',
 'Hrtvalvedx',
 'Carditis',
 'HTN',
 'Htncomplicn']

In [6]:
data = pd.read_table('mimic_synthetic_train.data',sep=' ',header=None)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [7]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,332,333,334,335,336,337,338,339,340,341
0,0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,...,0,0,0,0,0,0.0,0,0,0,0
1,1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,...,0,0,0,0,0,0.0,0,0,0,1
2,2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,...,0,0,0,0,0,0.0,0,0,0,0
3,3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,...,0,0,0,0,0,0.0,0,0,1,0
4,4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,...,0,0,0,0,0,0.0,0,0,0,0

In [8]:
data.drop(0,axis=1,inplace=True)

In [9]:
data

,1,2,3,4,5,6,7,8,9,10,...,332,333,334,335,336,337,338,339,340,341
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0,0.0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0,0.0,0,0,0,0
5,11634,144424,2147-08-30_19:51:00,2136-11-19_18:53:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
6,9259,189252,2144-04-26_22:49:00,2199-06-24_10:49:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
7,43732,128084,2194-04-12_01:19:00,2118-09-30_19:00:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,0
8,17978,167487,2159-10-13_23:08:00,2179-09-14_15:40:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
9,25610,151971,2119-08-01_07:15:00,2141-09-26_13:15:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
10,1999,144515,2171-09-11_15:27:00,2153-02-20_18:00:00,Medicare,SPAN,PROTESTANT_QUAKER,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,1
11,20651,177259,2145-02-17_17:20:00,2107-09-16_04:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
12,25707,123780,2110-09-17_22:22:00,2198-09-18_16:14:00,Medicare,ENGL,PROTESTANT_QUAKER,DIVORCED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
13,29887,171410,2192-10-13_18:24:00,2193-05-24_15:25:00,Self_Pay,SPAN,PROTESTANT_QUAKER,SINGLE,HISPANIC/LATINO_-_GUATEMALAN,F,...,0,0,0,0,0,0.0,0,0,1,0
14,20201,187451,2177-05-25_16:25:00,2106-05-21_13:00:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
15,48233,171452,2198-06-01_07:15:00,2160-12-11_07:11:00,Government,ENGL,PROTESTANT_QUAKER,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
16,95118,192883,2166-04-09_18:59:00,2193-05-06_16:10:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
17,13288,150512,2172-06-25_07:15:00,2163-10-08_16:00:00,Medicare,ENGL,CATHOLIC,SINGLE,BLACK/AFRICAN_AMERICAN,F,...,0,0,0,0,0,0.0,0,0,1,0
18,88252,105206,2186-01-29_18:30:00,2146-06-16_14:37:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
19,53215,128693,2103-12-28_02:14:00,2130-11-04_19:46:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
20,7547,107732,2140-01-13_21:25:00,2100-12-25_14:48:00,Private,ENGL,JEWISH,MARRIED,BLACK/HAITIAN,F,...,0,0,0,0,0,0.0,0,0,0,0
21,87918,191735,2191-07-01_22:13:00,2121-10-10_17:28:00,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
22,70164,157197,2133-10-06_05:14:00,2121-07-05_14:15:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
23,72364,188862,2161-07-29_20:05:00,2120-01-04_14:35:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
24,57773,188304,2151-05-27_18:47:00,2189-09-10_15:45:00,Private,ENGL,PROTESTANT_QUAKER,SINGLE,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
25,76017,183679,2155-01-30_00:05:00,2146-12-29_19:03:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
26,10475,140660,2162-05-30_13:07:00,2169-09-22_12:45:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,1,0
27,40519,142868,2121-02-20_01:05:00,2179-11-17_13:25:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
28,19473,113081,2133-04-28_07:15:00,2151-07-14_19:35:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
29,12791,145253,2127-12-16_07:15:00,2188-05-11_15:55:00,Medicaid,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,26668,193566,2181-04-27_23:34:00,2178-08-07_13:58:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
79970,46315,141848,2147-02-10_17:39:00,2150-11-19_11:45:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79971,12510,190855,2131-12-04_19:48:00,2197-05-30_16:45:00,Medicaid,ENGL,OTHER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79972,16322,169887,2172-12-08_07:15:00,2192-01-07_16:30:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79973,30236,110651,2176-09-26_02:09:00,2108-04-06_11:50:00,Private,ENGL,JEWISH,MARRIED,HISPANIC_OR_LATINO,F,...,0,0,0,0,0,0.0,1,0,0,1
79974,10012,187978,2180-05-16_19:40:00,2176-12-19_19:30:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79975,88728,127716,2155-04-20_21:28:00,2167-06-23_19:30:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79976,79348,107589,2151-05-04_21:00:00,2131-09-04_13:00:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79977,6873,135107,2143-12-24_05:28:00,2176-11-26_13:35:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,1,0
79978,17630,109400,2143-03-11_07:55:00,2136-03-20_18:30:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79979,86648,115071,2143-08-23_14:40:00,2201-03-12_15:30:00,Medicare,ENGL,PROTESTANT_QUAKER,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79980,28018,105487,2167-12-18_07:15:00,2138-06-04_20:02:00,Medicare,ENGL,JEWISH,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,1,0,1,1
79981,31039,138637,2196-04-20_19:27:00,2132-02-06_16:25:00,Private,ENGL,PROTESTANT_QUAKER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79982,67619,182950,2162-03-22_13:00:00,2139-08-07_14:55:00,Medicare,ENGL,JEWISH,SINGLE,ASIAN_-_CHINESE,M,...,0,0,0,0,0,0.0,0,0,1,0
79983,72113,127201,2111-06-09_22:57:00,2102-09-28_11:19:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79984,72849,153408,2116-07-06_18:59:00,2141-02-06_15:49:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79985,86108,159149,2124-09-15_15:55:00,2171-04-21_12:24:00,Private,ENGL,JEWISH,SINGLE,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
79986,11603,139934,2132-10-14_23:11:00,2125-11-15_14:38:00,Medicare,ENGL,CATHOLIC,DIVORCED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79987,25105,162373,2136-06-12_19:34:00,2198-09-25_18:20:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79988,74215,124569,2167-03-30_07:15:00,2143-09-04_13:01:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79989,60175,174292,2143-12-04_21:36:00,2152-05-27_13:00:00,Government,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79990,49261,192410,2162-09-24_07:15:00,2113-08-05_17:10:00,Government,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79991,28108,136094,2122-11-25_17:58:00,2144-03-21_16:30:00,Medicare,ENGL,JEWISH,WIDOWED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
79992,28791,168587,2149-05-30_10:45:00,2148-08-31_14:46:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,1
79993,98639,191596,2197-01-13_19:43:00,2203-10-27_15:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79994,63788,148874,2196-08-05_16:06:00,2135-02-10_14:15:00,Medicare,ENGL,NOT_SPECIFIED,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79995,22326,119010,2167-10-06_18:35:00,2121-01-01_16:04:00,Medicaid,ENGL,JEWISH,MARRIED,WHITE,F,...,0,0,0,0,0,1.0,0,0,0,0
79996,81274,183388,2143-04-04_10:30:00,2141-08-09_13:30:00,Private,ENGL,NOT_SPECIFIED,SEPARATED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79997,16587,151289,2183-12-03_02:50:00,2101-08-05_16:00:00,Government,ENGL,CATHOLIC,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79998,17643,145064,2184-05-27_23:46:00,2128-08-04_17:20:00,Government,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0

In [10]:
data.columns = name_col

In [11]:
data

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Eyeinfectn,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0,0.0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0,0.0,0,0,0,0
5,11634,144424,2147-08-30_19:51:00,2136-11-19_18:53:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
6,9259,189252,2144-04-26_22:49:00,2199-06-24_10:49:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
7,43732,128084,2194-04-12_01:19:00,2118-09-30_19:00:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,0
8,17978,167487,2159-10-13_23:08:00,2179-09-14_15:40:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
9,25610,151971,2119-08-01_07:15:00,2141-09-26_13:15:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
10,1999,144515,2171-09-11_15:27:00,2153-02-20_18:00:00,Medicare,SPAN,PROTESTANT_QUAKER,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,1
11,20651,177259,2145-02-17_17:20:00,2107-09-16_04:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
12,25707,123780,2110-09-17_22:22:00,2198-09-18_16:14:00,Medicare,ENGL,PROTESTANT_QUAKER,DIVORCED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
13,29887,171410,2192-10-13_18:24:00,2193-05-24_15:25:00,Self_Pay,SPAN,PROTESTANT_QUAKER,SINGLE,HISPANIC/LATINO_-_GUATEMALAN,F,...,0,0,0,0,0,0.0,0,0,1,0
14,20201,187451,2177-05-25_16:25:00,2106-05-21_13:00:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
15,48233,171452,2198-06-01_07:15:00,2160-12-11_07:11:00,Government,ENGL,PROTESTANT_QUAKER,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
16,95118,192883,2166-04-09_18:59:00,2193-05-06_16:10:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
17,13288,150512,2172-06-25_07:15:00,2163-10-08_16:00:00,Medicare,ENGL,CATHOLIC,SINGLE,BLACK/AFRICAN_AMERICAN,F,...,0,0,0,0,0,0.0,0,0,1,0
18,88252,105206,2186-01-29_18:30:00,2146-06-16_14:37:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
19,53215,128693,2103-12-28_02:14:00,2130-11-04_19:46:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
20,7547,107732,2140-01-13_21:25:00,2100-12-25_14:48:00,Private,ENGL,JEWISH,MARRIED,BLACK/HAITIAN,F,...,0,0,0,0,0,0.0,0,0,0,0
21,87918,191735,2191-07-01_22:13:00,2121-10-10_17:28:00,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
22,70164,157197,2133-10-06_05:14:00,2121-07-05_14:15:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
23,72364,188862,2161-07-29_20:05:00,2120-01-04_14:35:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
24,57773,188304,2151-05-27_18:47:00,2189-09-10_15:45:00,Private,ENGL,PROTESTANT_QUAKER,SINGLE,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
25,76017,183679,2155-01-30_00:05:00,2146-12-29_19:03:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
26,10475,140660,2162-05-30_13:07:00,2169-09-22_12:45:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,1,0
27,40519,142868,2121-02-20_01:05:00,2179-11-17_13:25:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
28,19473,113081,2133-04-28_07:15:00,2151-07-14_19:35:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
29,12791,145253,2127-12-16_07:15:00,2188-05-11_15:55:00,Medicaid,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,26668,193566,2181-04-27_23:34:00,2178-08-07_13:58:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
79970,46315,141848,2147-02-10_17:39:00,2150-11-19_11:45:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79971,12510,190855,2131-12-04_19:48:00,2197-05-30_16:45:00,Medicaid,ENGL,OTHER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79972,16322,169887,2172-12-08_07:15:00,2192-01-07_16:30:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79973,30236,110651,2176-09-26_02:09:00,2108-04-06_11:50:00,Private,ENGL,JEWISH,MARRIED,HISPANIC_OR_LATINO,F,...,0,0,0,0,0,0.0,1,0,0,1
79974,10012,187978,2180-05-16_19:40:00,2176-12-19_19:30:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79975,88728,127716,2155-04-20_21:28:00,2167-06-23_19:30:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79976,79348,107589,2151-05-04_21:00:00,2131-09-04_13:00:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79977,6873,135107,2143-12-24_05:28:00,2176-11-26_13:35:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,1,0
79978,17630,109400,2143-03-11_07:55:00,2136-03-20_18:30:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79979,86648,115071,2143-08-23_14:40:00,2201-03-12_15:30:00,Medicare,ENGL,PROTESTANT_QUAKER,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79980,28018,105487,2167-12-18_07:15:00,2138-06-04_20:02:00,Medicare,ENGL,JEWISH,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,1,0,1,1
79981,31039,138637,2196-04-20_19:27:00,2132-02-06_16:25:00,Private,ENGL,PROTESTANT_QUAKER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79982,67619,182950,2162-03-22_13:00:00,2139-08-07_14:55:00,Medicare,ENGL,JEWISH,SINGLE,ASIAN_-_CHINESE,M,...,0,0,0,0,0,0.0,0,0,1,0
79983,72113,127201,2111-06-09_22:57:00,2102-09-28_11:19:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79984,72849,153408,2116-07-06_18:59:00,2141-02-06_15:49:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79985,86108,159149,2124-09-15_15:55:00,2171-04-21_12:24:00,Private,ENGL,JEWISH,SINGLE,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
79986,11603,139934,2132-10-14_23:11:00,2125-11-15_14:38:00,Medicare,ENGL,CATHOLIC,DIVORCED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79987,25105,162373,2136-06-12_19:34:00,2198-09-25_18:20:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79988,74215,124569,2167-03-30_07:15:00,2143-09-04_13:01:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79989,60175,174292,2143-12-04_21:36:00,2152-05-27_13:00:00,Government,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79990,49261,192410,2162-09-24_07:15:00,2113-08-05_17:10:00,Government,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79991,28108,136094,2122-11-25_17:58:00,2144-03-21_16:30:00,Medicare,ENGL,JEWISH,WIDOWED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
79992,28791,168587,2149-05-30_10:45:00,2148-08-31_14:46:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,1
79993,98639,191596,2197-01-13_19:43:00,2203-10-27_15:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79994,63788,148874,2196-08-05_16:06:00,2135-02-10_14:15:00,Medicare,ENGL,NOT_SPECIFIED,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79995,22326,119010,2167-10-06_18:35:00,2121-01-01_16:04:00,Medicaid,ENGL,JEWISH,MARRIED,WHITE,F,...,0,0,0,0,0,1.0,0,0,0,0
79996,81274,183388,2143-04-04_10:30:00,2141-08-09_13:30:00,Private,ENGL,NOT_SPECIFIED,SEPARATED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79997,16587,151289,2183-12-03_02:50:00,2101-08-05_16:00:00,Government,ENGL,CATHOLIC,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79998,17643,145064,2184-05-27_23:46:00,2128-08-04_17:20:00,Government,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0

In [12]:
died = pd.read_table('mimic_synthetic_train.solution',sep='\n',header=None)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [13]:
died.head()

   0
0  0
1  0
2  0
3  0
4  0

In [14]:
died.columns = ['DIED']

In [15]:
died.head()

   DIED
0     0
1     0
2     0
3     0
4     0

In [16]:
data = pd.concat([data,died],axis=1)

In [17]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0.0,0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0.0,0,0,0,1,0
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0.0,0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0.0,0,0,1,0,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0.0,0,0,0,0,0

In [18]:
num_cols = []
categorical_col = []

for cols in data.columns:
    if data[cols].dtype == object:
        categorical_col.append(cols)
    else:
        num_cols.append(cols)

In [19]:
print('length of numerical columns',len(num_cols))
print('length of categorical columns',len(categorical_col))

length of numerical columns 333
length of categorical columns 9

In [20]:
data.describe()

,SUBJECT_ID,HADM_ID,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
count,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,...,79999.000000,79999.0,79999.0,79999.0,79998.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000
mean,37927.384230,150061.011025,62.660546,71.648531,103.083037,86.394036,94.612069,147.790712,119.655538,45.243690,...,0.000013,0.0,0.0,0.0,0.145454,0.134177,0.008625,0.457693,0.078976,0.034963
std,29300.394392,29005.267607,18.193723,14.652553,18.479082,15.510917,16.940341,21.609206,16.486749,10.499518,...,0.003536,0.0,0.0,0.0,0.352560,0.340844,0.092471,0.498210,0.269703,0.183687
min,3.000000,100001.000000,16.000000,18.728695,49.860610,38.503600,31.768501,91.693405,73.968796,11.334383,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13853.000000,124750.000000,51.000000,61.458639,89.897490,75.284898,82.811535,132.121700,107.559967,37.831446,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27591.000000,150045.000000,65.000000,71.049320,101.585940,85.421690,94.168460,145.412140,118.117890,44.621235,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,62471.000000,175452.000000,77.000000,81.148908,114.800830,96.505275,105.964120,161.115990,130.294615,51.966651,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,99999.000000,199999.000000,90.000000,141.859680,206.621150,157.612470,163.822920,260.044980,186.328400,95.604270,...,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
data[categorical_col].head()

,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,ICU
0,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,SICU
1,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,CCU
2,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,MICU
3,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,CCU
4,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,MICU

In [22]:
data['MARITAL_STATUS'].value_counts()

MARRIED              43661
SINGLE               18318
WIDOWED               9375
DIVORCED              5015
UNKNOWN_(DEFAULT)     2114
SEPARATED             1139
LIFE_PARTNER           376
Name: MARITAL_STATUS, dtype: int64

In [23]:
data['INSURANCE'].value_counts()

Medicare      44670
Private       23964
Medicaid       6434
Government     2933
Self_Pay       1998
Name: INSURANCE, dtype: int64

In [24]:
data.get_dtype_counts()

float64     51
int64      282
object       9
dtype: int64

In [25]:
data['ADMITTIME'] = data['ADMITTIME'].str.replace('_',' ')

In [26]:
data['ADMITTIME'] = pd.to_datetime(data['ADMITTIME'])

In [27]:
data['ADMITTIME'].dtype

dtype('<M8[ns]')

In [28]:
data['DISCHTIME'] = data['DISCHTIME'].str.replace('_',' ')

In [29]:
data['DISCHTIME'] = pd.to_datetime(data['DISCHTIME'])

In [30]:
data['DISCHTIME'].dtype

dtype('<M8[ns]')

In [31]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
0,45524,108398,2128-05-15 23:42:00,2132-07-23 15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0.0,0,0,0,0,0
1,50520,186416,2134-03-17 03:59:00,2113-03-06 12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0.0,0,0,0,1,0
2,17956,126413,2164-04-05 17:32:00,2180-09-20 16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0.0,0,0,0,0,0
3,90258,109355,2102-09-08 00:58:00,2166-06-26 15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0.0,0,0,1,0,0
4,25159,123784,2163-08-06 12:07:00,2147-01-14 18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0.0,0,0,0,0,0

In [32]:
data['ETHNICITY'].value_counts()

WHITE                                                       59728
UNKNOWN/NOT_SPECIFIED                                        4343
BLACK/AFRICAN_AMERICAN                                       3718
OTHER                                                        1647
HISPANIC_OR_LATINO                                           1429
ASIAN                                                        1416
UNABLE_TO_OBTAIN                                             1384
PATIENT_DECLINED_TO_ANSWER                                   1085
ASIAN_-_CHINESE                                               541
HISPANIC/LATINO_-_PUERTO_RICAN                                466
BLACK/CAPE_VERDEAN                                            426
WHITE_-_RUSSIAN                                               393
MULTI_RACE_ETHNICITY                                          357
HISPANIC/LATINO_-_DOMINICAN                                   290
BLACK/HAITIAN                                                 267
WHITE_-_OTHER_EUROPEAN                                        266
ASIAN_-_ASIAN_INDIAN                                          246
PORTUGUESE                                                    213
WHITE_-_BRAZILIAN                                             205
ASIAN_-_VIETNAMESE                                            189
BLACK/AFRICAN                                                 176
HISPANIC/LATINO_-_GUATEMALAN                                  136
AMERICAN_INDIAN/ALASKA_NATIVE                                 132
MIDDLE_EASTERN                                                120
WHITE_-_EASTERN_EUROPEAN                                      101
ASIAN_-_OTHER                                                  89
HISPANIC/LATINO_-_CUBAN                                        83
ASIAN_-_FILIPINO                                               65
HISPANIC/LATINO_-_CENTRAL_AMERICAN_(OTHER)                     62
NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER                      60
ASIAN_-_KOREAN                                                 60
ASIAN_-_CAMBODIAN                                              60
HISPANIC/LATINO_-_MEXICAN                                      49
HISPANIC/LATINO_-_COLOMBIAN                                    46
SOUTH_AMERICAN                                                 46
CARIBBEAN_ISLAND                                               37
ASIAN_-_JAPANESE                                               31
HISPANIC/LATINO_-_SALVADORAN                                   20
ASIAN_-_THAI                                                   10
HISPANIC/LATINO_-_HONDURAN                                      6
AMERICAN_INDIAN/ALASKA_NATIVE_FEDERALLY_RECOGNIZED_TRIBE        1
Name: ETHNICITY, dtype: int64

In [33]:
data[num_cols].describe()

,SUBJECT_ID,HADM_ID,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
count,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,...,79999.000000,79999.0,79999.0,79999.0,79998.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000
mean,37927.384230,150061.011025,62.660546,71.648531,103.083037,86.394036,94.612069,147.790712,119.655538,45.243690,...,0.000013,0.0,0.0,0.0,0.145454,0.134177,0.008625,0.457693,0.078976,0.034963
std,29300.394392,29005.267607,18.193723,14.652553,18.479082,15.510917,16.940341,21.609206,16.486749,10.499518,...,0.003536,0.0,0.0,0.0,0.352560,0.340844,0.092471,0.498210,0.269703,0.183687
min,3.000000,100001.000000,16.000000,18.728695,49.860610,38.503600,31.768501,91.693405,73.968796,11.334383,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13853.000000,124750.000000,51.000000,61.458639,89.897490,75.284898,82.811535,132.121700,107.559967,37.831446,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27591.000000,150045.000000,65.000000,71.049320,101.585940,85.421690,94.168460,145.412140,118.117890,44.621235,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,62471.000000,175452.000000,77.000000,81.148908,114.800830,96.505275,105.964120,161.115990,130.294615,51.966651,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,99999.000000,199999.000000,90.000000,141.859680,206.621150,157.612470,163.822920,260.044980,186.328400,95.604270,...,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [34]:
from sklearn.impute import SimpleImputer

In [35]:
imputer = SimpleImputer(strategy='median')

In [36]:
data[num_cols] = imputer.fit_transform(data[num_cols])

In [37]:
data = pd.get_dummies(data)

In [38]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,...,ETHNICITY_WHITE_-_EASTERN_EUROPEAN,ETHNICITY_WHITE_-_OTHER_EUROPEAN,ETHNICITY_WHITE_-_RUSSIAN,GENDER_F,GENDER_M,ICU_CCU,ICU_CSRU,ICU_MICU,ICU_SICU,ICU_TSICU
0,45524.0,108398.0,2128-05-15 23:42:00,2132-07-23 15:00:00,21.0,57.207630,108.704030,70.841980,79.847060,119.72417,...,0,0,0,1,0,0,0,0,1,0
1,50520.0,186416.0,2134-03-17 03:59:00,2113-03-06 12:05:00,39.0,79.331400,121.138664,96.915726,93.994540,138.59406,...,0,0,0,0,1,1,0,0,0,0
2,17956.0,126413.0,2164-04-05 17:32:00,2180-09-20 16:30:00,40.0,118.230290,175.175430,140.936700,122.862610,144.25964,...,0,0,0,0,1,0,0,1,0,0
3,90258.0,109355.0,2102-09-08 00:58:00,2166-06-26 15:30:00,75.0,83.780380,89.188980,86.051155,111.390740,144.86057,...,0,0,0,0,1,1,0,0,0,0
4,25159.0,123784.0,2163-08-06 12:07:00,2147-01-14 18:40:00,55.0,60.878613,105.637500,80.616840,87.627464,127.75874,...,0,0,0,1,0,0,0,1,0,0

In [39]:
temp = pd.CategoricalDtype(data)